# Borrowed heavily from https://github.com/MyIntervals/emogrifier/blob/master/.github/workflows/ci.yml
name: CI

on:
  - pull_request
  - push

jobs:
  php-lint:
    name: PHP Lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: PHP Lint
        run: composer lint

  composer-validate:
    name: Composer Validate

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer Validate
        run: composer validate --no-check-all --no-check-lock --strict

  static-analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    needs: [php-lint, composer-validate]

    strategy:
      matrix:
        command:
          - cs-check
        php-version:
          - 7.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: Run Command
        run: composer ci:${{ matrix.command }}

  unit-tests:
    name: Unit tests

    runs-on: ubuntu-latest

    needs: [php-lint, composer-validate]

    strategy:
      matrix:
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
        dependencies:
          - lowest
          - highest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: xdebug.max_nesting_level=500

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: Install Composer dependencies
        run: |
          if [[ "${{ matrix.dependencies }}" == 'lowest' ]]; then
            DEPENDENCIES='--prefer-lowest';
          else
            DEPENDENCIES='';
          fi;
          composer update --no-progress "${DEPENDENCIES}";
          composer show;

      - name: Run Tests
        run: composer ci:tests
